# board: [seeeduino_xiao_ble]
# shield: [swoon]

include:
  - board:  seeeduino_xiao_ble
    shield: swoon_left
    artifact-name: swoon_qwerty_left
  - board:  seeeduino_xiao_ble
    shield: swoon_right
    artifact-name: swoon_qwerty_right

  - board:  seeeduino_xiao_ble
    shield: swoon_left
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DLAYOUT=1
    artifact-name: swoon_engram_left
  - board:  seeeduino_xiao_ble
    shield: swoon_right
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DLAYOUT=1
    artifact-name: swoon_engram_right
    
  - board:  seeeduino_xiao_ble
    shield: swoon_left
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DLAYOUT=2
    artifact-name: swoon_engrammer_left
  - board:  seeeduino_xiao_ble
    shield: swoon_right
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DLAYOUT=2
    artifact-name: swoon_engrammer_right
