name: Build123d Case

on:
  workflow_run:
    workflows: ["KiBot Check & Generate"]
    types:
      - completed
  workflow_dispatch:

jobs:
  Case:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: BOARD_OUTLINE
        path: case/swoon_edges.svg
        run-id: ${{ github.event.workflow_run.id }}
    - run: |
        python3 -m pip install vpype build123d
        vpype read case/swoon_edges.svg linemerge --tolerance 3mm linesort reloop \
          linesimplify write case/swoon_edges_vpype.svg
        python case.py
    - uses: actions/upload-artifact@v4
      with:
        name: Case_STEP
        path: "*.step"
    - uses: actions/upload-artifact@v4
      with:
        name: Case_STL
        path: "*.stl"
