name: "KiBot Check & Generate"

# Controls when the action will run.
on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot.yml'
  repository_dispatch:
    types: [run_gha]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run ERC
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: Generated
        skip: drc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC_Output
        path: Generated/*.html

  DRC:
    runs-on: ubuntu-latest
    needs: ERC

    steps:
    - uses: actions/checkout@v4

    - name: Run DRC
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: Generated
        skip: erc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: DRC_Output
        path: Generated/*.html

  flip:
    name: "flip"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: default
        variant: flip
        skip: erc,drc

    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: JLCPCB
        path: default/*.zip

  left:
    name: "left"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: default
        variant: left
        skip: erc,drc

    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: JLCPCB
        path: default/*.zip

  right:
    name: "right"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]

    steps:
    - uses: actions/checkout@v4

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        dir: default
        variant: right
        skip: erc,drc

    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: JLCPCB
        path: default/*.zip

