name: "KiBot Check & Generate"

# Controls when the action will run.
on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot.yml'
  repository_dispatch:
    types: [run_gha]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ERC
      uses: INTI-CMNB/KiBot@v2_dk8
      with:
        dir: Generated
        skip: drc
        targets: __NONE__
    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC_Output
        path: Generated/*.html

  DRC:
    runs-on: ubuntu-latest
    needs: ERC
    steps:
    - uses: actions/checkout@v4
    - name: Run DRC
      uses: INTI-CMNB/KiBot@v2_dk8
      with:
        dir: Generated
        skip: erc
        targets: __NONE__
    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: DRC_Output
        path: Generated/*.html

  FLIP:
    runs-on: ubuntu-latest
    needs: [ERC, DRC]
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_dk8
      with:
        dir: default
        variant: flip
        skip: erc,drc
        targets: SCHEMATIC EDGES JLCPCB_GERBERS JLCPCB_DRILL JLCPCB_ZIP
    - name: upload schematic
      uses: actions/upload-artifact@v4
      with:
        name: SCHEMATIC_SVG
        path: default/*schematic*.svg
    - name: upload board outline
      uses: actions/upload-artifact@v4
      with:
        name: BOARD_OUTLINE
        path: default/*edge*.svg
    - name: upload drill
      uses: actions/upload-artifact@v4
      with:
        name: JLCPCB_DRILL
        path: default/JLCPCB_DRILL/
    - name: upload compressed gerbers and drill
      uses: actions/upload-artifact@v4
      with:
        name: SWOON_FLIP
        path: default/*.zip

  LEFT:
    runs-on: ubuntu-latest
    needs: [ERC, DRC, FLIP]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: JLCPCB_DRILL
    - uses: INTI-CMNB/KiBot@v2_dk8
      with:
        dir: default
        variant: left
        skip: erc,drc
        targets: JLCPCB_GERBERS JLCPCB_POSITION JLCPCB_BOM STEP JLCPCB_ZIP JLCPCB_ZIP_ALL
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: SWOON_LEFT
        path: default/*ALL*.zip

  RIGHT:
    runs-on: ubuntu-latest
    needs: [ERC, DRC, FLIP]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: JLCPCB_DRILL
    - uses: INTI-CMNB/KiBot@v2_dk8
      with:
        dir: default
        variant: right
        skip: erc,drc
        targets: JLCPCB_GERBERS JLCPCB_POSITION JLCPCB_BOM STEP JLCPCB_ZIP JLCPCB_ZIP_ALL
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: SWOON_RIGHT
        path: default/*ALL*.zip


  CLEAN:
    runs-on: ubuntu-latest
    needs: [ERC, DRC, FLIP, LEFT, RIGHT]
    steps:   
    - uses: geekyeggo/delete-artifact@v5
      with:
        name: |
          JLCPCB_DRILL
          DRC_Output
          ERC_Output
